# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: BMO-Prod/template_repo
#       endpoint: github.com_sa-onboarding_bmogc
#       ref: refs/tags/v1.1.0

resources:
  repositories:
    - repository: templates
      type: github
      name: mehedi02/Docker_for_DevOps
      # endpoint: github.com_sa-onboarding_bmogc
      # ref: refs/tags/v1.1.0

variables:
- group: AnsibleVar

pool:
  name: Default

steps:
- script: echo $(ansibleInventory)
- script: echo $(ansiblePassword)

# stages:
# - template: pipeline_templates/release.yml@templates
#   parameters:
#     agentPoolName: 'Prod'
#     agentOS: 'Linux'
#     jobTimeoutInMinutes: 180
#     defaultVariables:
#       __default__:
#         envName: Dev
#         ansibleUsername : $(tower_user)
#         ansiblePassword : $(tower_password)
#         ansibleInventory: 'DevOpsCITools_DTOP_Dev'
#         ansibleJobTemplate: 'DevOpsCITools_SampleApp_Install'
#         ansibleProject: 'DevOpsCITools_DTOP_Dev'
#         ansibleRelease: 'Bamboo_Test_Release_Value'
#         ansibleApiHost: ansible.bmogc.net
#     customVariables:
#       Deploy:
#         additionalAnsibleArguments: '--install_host="cmtoldsdlcapp14.dev.bmocm.com" --install_dir="/apps/sdlctools/webdesign/testAnsible" --install_binary="DevOpsCITools-Virtual/DTOP/BMOAgileApp-5.0.2+DTOP+1.zip"'
