# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: BMO-Prod/template_repo
#       endpoint: github.com_sa-onboarding_bmogc
#       ref: refs/tags/v1.1.0
# trigger:
#   branches:
#     include:
#     - dev
#     - main
#     - releases/*
#     - hotfixes/*
#     - features/*
trigger:
  branches:
    exclude:
      - main
  paths:
    include:
      - '*'


resources:
  repositories:
    - repository: templates
      type: github
      name: mehedi02/spring_boot_test
      endpoint: mehedi02
      # ref: refs/tags/v1.1.0

variables:
- group: AnsibleVar

pool:
  name: Default

steps:
- script: echo $(ansibleInventory)
- script: echo $(ansiblePassword)
- task: PowerShell@2
  inputs:
    filePath: 'test.ps1'
- script: |
      # echo $(Build.SourceBranch) # This will output the source branch name in the format 'refs/heads/<branch-name>'
      echo $(Build.SourceBranchName) 
      # This will output the source branch name without the 'refs/heads/' prefix

# stages:
# - template: pipeline_templates/release.yml@templates
#   parameters:
#     agentPoolName: 'Prod'
#     agentOS: 'Linux'
#     jobTimeoutInMinutes: 180
#     defaultVariables:
#       __default__:
#         envName: Dev
#         ansibleUsername : $(tower_user)
#         ansiblePassword : $(tower_password)
#         ansibleInventory: 'DevOpsCITools_DTOP_Dev'
#         ansibleJobTemplate: 'DevOpsCITools_SampleApp_Install'
#         ansibleProject: 'DevOpsCITools_DTOP_Dev'
#         ansibleRelease: 'Bamboo_Test_Release_Value'
#         ansibleApiHost: ansible.bmogc.net
#     customVariables:
#       Deploy:
#         additionalAnsibleArguments: '--install_host="cmtoldsdlcapp14.dev.bmocm.com" --install_dir="/apps/sdlctools/webdesign/testAnsible" --install_binary="DevOpsCITools-Virtual/DTOP/BMOAgileApp-5.0.2+DTOP+1.zip"'
